//===----------------------------------------------------------------------===//
//                         DuckDB
//
// duckdb/main/extension_entries.hpp
//
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/common/common.hpp"
#include "duckdb/common/enums/catalog_type.hpp"

// NOTE: the autoload metadata exposed through this header is generated by scripts/generate_extensions_function.py.
// Example usage to refresh one extension (replace "icu" with the desired extension):
// GENERATE_EXTENSION_ENTRIES=1 make debug
// python3 scripts/generate_extensions_function.py --extensions icu --shell build/debug/duckdb --extension_repository
// build/debug/repository

// Check out the check-load-install-extensions job in .github/workflows/LinuxRelease.yml for more details

#ifndef DUCKDB_EXTENSION_ENTRIES_API
#if defined(_WIN32) && defined(DUCKDB_EXTENSION_ENTRIES_BUILD)
#define DUCKDB_EXTENSION_ENTRIES_API __declspec(dllexport)
#elif defined(_WIN32)
#define DUCKDB_EXTENSION_ENTRIES_API __declspec(dllimport)
#else
#define DUCKDB_EXTENSION_ENTRIES_API
#endif
#endif

namespace duckdb {

struct ExtensionEntry {
	char name[48];
	char extension[48];
};

struct ExtensionFunctionEntry {
	char name[48];
	char extension[48];
	CatalogType type;
};

struct ExtensionFunctionOverloadEntry {
	char name[48];
	char extension[48];
	CatalogType type;
	char signature[96];
};

struct DuckDBExtensionEntriesV1 {
	uint32_t abi_version;

	const ExtensionFunctionEntry *functions;
	idx_t functions_count;

	const ExtensionFunctionOverloadEntry *function_overloads;
	idx_t function_overloads_count;

	const ExtensionEntry *settings;
	idx_t settings_count;

	const ExtensionEntry *secret_types;
	idx_t secret_types_count;

	const ExtensionEntry *copy_functions;
	idx_t copy_functions_count;

	const ExtensionEntry *types;
	idx_t types_count;

	const ExtensionEntry *collations;
	idx_t collations_count;

	const ExtensionEntry *file_prefixes;
	idx_t file_prefixes_count;

	const ExtensionEntry *file_postfixes;
	idx_t file_postfixes_count;

	const ExtensionEntry *file_contains;
	idx_t file_contains_count;

	const ExtensionEntry *secret_providers;
	idx_t secret_providers_count;

	const char *const *autoloadable_extensions;
	idx_t autoloadable_extensions_count;

	const char *default_extension_directories;
};

extern "C" DUCKDB_EXTENSION_ENTRIES_API const DuckDBExtensionEntriesV1 *duckdb_extension_entries_v1();

class ExtensionEntries {
public:
	static const DuckDBExtensionEntriesV1 &Get();
	static const char *DefaultExtensionDirectories();
};

enum class ExtensionEntryKind : uint8_t {
	SETTINGS,
	SECRET_TYPES,
	COPY_FUNCTIONS,
	TYPES,
	COLLATIONS,
	FILE_PREFIXES,
	FILE_POSTFIXES,
	FILE_CONTAINS,
	SECRET_PROVIDERS
};

class ExtensionEntryCollection {
public:
	typedef ExtensionEntry value_type;

	constexpr explicit ExtensionEntryCollection(ExtensionEntryKind kind) : kind(kind) {
	}

	const ExtensionEntry *begin() const;
	const ExtensionEntry *end() const;
	idx_t size() const;
	const ExtensionEntry &operator[](idx_t index) const;

private:
	const ExtensionEntry *data() const;

private:
	ExtensionEntryKind kind;
};

class ExtensionFunctionEntryCollection {
public:
	typedef ExtensionFunctionEntry value_type;

	const ExtensionFunctionEntry *begin() const;
	const ExtensionFunctionEntry *end() const;
	idx_t size() const;
	const ExtensionFunctionEntry &operator[](idx_t index) const;

private:
	const ExtensionFunctionEntry *data() const;
};

class ExtensionFunctionOverloadEntryCollection {
public:
	typedef ExtensionFunctionOverloadEntry value_type;

	const ExtensionFunctionOverloadEntry *begin() const;
	const ExtensionFunctionOverloadEntry *end() const;
	idx_t size() const;
	const ExtensionFunctionOverloadEntry &operator[](idx_t index) const;

private:
	const ExtensionFunctionOverloadEntry *data() const;
};

class AutoloadableExtensionCollection {
public:
	typedef const char *value_type;

	const char *const *begin() const;
	const char *const *end() const;
	idx_t size() const;
	const char *operator[](idx_t index) const;

private:
	const char *const *data() const;
};

static const ExtensionFunctionEntryCollection EXTENSION_FUNCTIONS;
static const ExtensionFunctionOverloadEntryCollection EXTENSION_FUNCTION_OVERLOADS;
static const ExtensionEntryCollection EXTENSION_SETTINGS(ExtensionEntryKind::SETTINGS);
static const ExtensionEntryCollection EXTENSION_SECRET_TYPES(ExtensionEntryKind::SECRET_TYPES);
static const ExtensionEntryCollection EXTENSION_COPY_FUNCTIONS(ExtensionEntryKind::COPY_FUNCTIONS);
static const ExtensionEntryCollection EXTENSION_TYPES(ExtensionEntryKind::TYPES);
static const ExtensionEntryCollection EXTENSION_COLLATIONS(ExtensionEntryKind::COLLATIONS);
static const ExtensionEntryCollection EXTENSION_FILE_PREFIXES(ExtensionEntryKind::FILE_PREFIXES);
static const ExtensionEntryCollection EXTENSION_FILE_POSTFIXES(ExtensionEntryKind::FILE_POSTFIXES);
static const ExtensionEntryCollection EXTENSION_FILE_CONTAINS(ExtensionEntryKind::FILE_CONTAINS);
static const ExtensionEntryCollection EXTENSION_SECRET_PROVIDERS(ExtensionEntryKind::SECRET_PROVIDERS);
static const AutoloadableExtensionCollection AUTOLOADABLE_EXTENSIONS;

} // namespace duckdb
